version: '3.8'

services:
  frontend:
    environment:
      CHOKIDAR_USEPOLLING: "true"
      FAST_REFRESH: "true"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/code
      - /code/node_modules
